apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
        - name: note
          image: akhilgandhilive/note-app:1.0.0
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: note-app
spec:
  selector:
    app: note-app
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer